#########################################################################
# BungeePing by xDefcon - Configuration file
# https://www.spigotmc.org/resources/bungeeping.16840/
# Please check for updates, and remember to update the config if needed!
#########################################################################

# Section releated to the /ping command.
ping-command:
  # Customize the output of the command, use %ping% to indicate player's latency.
  ping-message: "&a[Ping] &7Your ping is: &a%ping%ms"
  # Customize the output of the command to check the ping of another player (if enabled).
  # Use %target% to indicate the name of the target player, use %ping% to indicate player's latency.
  ping-target-message: "&a[Ping] &7The ping of &a%target% &7is: &a%ping%ms"

# Section releated to the per command permission system.
permission-system:
  # Set this to true if you want to enable the permission system.
  enabled: false
  # Customize the message sent to the players if they do not have required permission.
  no-perm-message: "&cYou do not have permission to execute this command."

# Section releated to the /ping <targetPlayer> command
others-ping:
  # Set this to false if you want to DISALLOW users to check the ping of another player.
  show-other-players-ping: true
  # Customize the message sent to the players if they do not have required permission.
  not-allowed-message: "&cYou do not have permission to check the ping of other players."
  # Customize the message sent to the players if the specified player can not be found.
  player-not-found: "&cThe specified player is not online."
